---
# This file was generated; to regnerated `cd` to `pipeline_generator`
# and run:
#
#    make > ../bitbucket-pipelines.yml

image: debian:buster
options:
  size: 2x

definitions:
  services:
    docker:
      memory: 4096

pipelines:
  default:
    - step:
        name: Pre Parallelization stage
        script:
          - echo "Running tests in 36 batches"

    - step:
        name: Check if the template is up-to-date
        script:
          - |
              actual_scenario_count=$(find ./roles -type f -name "molecule.yml" -exec dirname {} ';' | wc -l |  sed -e 's/^[[:space:]]*//')
              grep  "Running tests in ${actual_scenario_count} batches" bitbucket-pipelines.yml
              GREP_RETURN_CODE=$?
              if [[ $GREP_RETURN_CODE -ne 0 ]]; then
                  echo "Mismatch between expected and actual number [${actual_scenario_count}] of scenarios. Please look at https://bitbucket.org/atlassian/dc-deployments-automation/src/master/DEVELOPMENT.md for instructions on how to fix this error."
                  exit $GREP_RETURN_CODE
              fi

    - parallel:
        - step:
           name: aws_common/cw-disabled
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/aws_common
             - pipenv run molecule test -s cw-disabled
        - step:
           name: aws_common/default
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/aws_common
             - pipenv run molecule test -s default
        - step:
           name: aws_common/logs-disabled
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/aws_common
             - pipenv run molecule test -s logs-disabled
        - step:
           name: bitbucket_config/default
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/bitbucket_config
             - pipenv run molecule test -s default
        - step:
           name: bitbucket_config/iam_elasticsearch
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/bitbucket_config
             - pipenv run molecule test -s iam_elasticsearch
        - step:
           name: confluence_config/aurora
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/confluence_config
             - pipenv run molecule test -s aurora
        - step:
           name: confluence_config/default
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/confluence_config
             - pipenv run molecule test -s default
        - step:
           name: confluence_config/password_char_escaping
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/confluence_config
             - pipenv run molecule test -s password_char_escaping
        - step:
           name: confluence_config/system_jdk
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/confluence_config
             - pipenv run molecule test -s system_jdk
        - step:
           name: diy_backup/default
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/diy_backup
             - pipenv run molecule test -s default
        - step:
           name: jira_config/aurora
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/jira_config
             - pipenv run molecule test -s aurora
        - step:
           name: jira_config/default
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/jira_config
             - pipenv run molecule test -s default
        - step:
           name: jira_config/jira_config_props
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/jira_config
             - pipenv run molecule test -s jira_config_props
        - step:
           name: jira_config/password_char_escaping
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/jira_config
             - pipenv run molecule test -s password_char_escaping
        - step:
           name: linux_common/default
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/linux_common
             - pipenv run molecule test -s default
        - step:
           name: product_common/default
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_common
             - pipenv run molecule test -s default
        - step:
           name: product_common/system_jdk
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_common
             - pipenv run molecule test -s system_jdk
        - step:
           name: product_install/bitbucket_latest
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_install
             - pipenv run molecule test -s bitbucket_latest
        - step:
           name: product_install/confluence_latest
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_install
             - pipenv run molecule test -s confluence_latest
        - step:
           name: product_install/crowd_latest
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_install
             - pipenv run molecule test -s crowd_latest
        - step:
           name: product_install/default
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_install
             - pipenv run molecule test -s default
        - step:
           name: product_install/jira_all
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_install
             - pipenv run molecule test -s jira_all
        - step:
           name: product_install/jira_all_version_url
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_install
             - pipenv run molecule test -s jira_all_version_url
        - step:
           name: product_install/jira_cached_with_downgrade
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_install
             - pipenv run molecule test -s jira_cached_with_downgrade
        - step:
           name: product_install/jira_cached_with_upgrade
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_install
             - pipenv run molecule test -s jira_cached_with_upgrade
        - step:
           name: product_install/jira_software_latest
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_install
             - pipenv run molecule test -s jira_software_latest
        - step:
           name: product_install/jira_tarball
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_install
             - pipenv run molecule test -s jira_tarball
        - step:
           name: product_install/jira_version_from_file
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_install
             - pipenv run molecule test -s jira_version_from_file
        - step:
           name: product_install/jira_version_latest
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_install
             - pipenv run molecule test -s jira_version_latest
        - step:
           name: product_install/jira_version_override
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_install
             - pipenv run molecule test -s jira_version_override
        - step:
           name: product_install/servicedesk3
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_install
             - pipenv run molecule test -s servicedesk3
        - step:
           name: product_install/servicedesk4
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_install
             - pipenv run molecule test -s servicedesk4
        - step:
           name: product_install/servicedesk_latest
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_install
             - pipenv run molecule test -s servicedesk_latest
        - step:
           name: product_startup/bitbucket
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_startup
             - pipenv run molecule test -s bitbucket
        - step:
           name: product_startup/default
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_startup
             - pipenv run molecule test -s default
        - step:
           name: product_startup/startup_restart_false
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_startup
             - pipenv run molecule test -s startup_restart_false
        - step:
           name: product_startup/synchrony
           services:
             - docker
           script:
             - export ANSIBLE_CONFIG=./ansible.cfg
             - ./bin/install-ansible --dev
             - cd roles/product_startup
             - pipenv run molecule test -s synchrony
        - step:
           name: Run Snyk security scan
           services:
             - docker
           script:
             - ./bin/install-ansible --dev
             - apt-get update && apt-get install -y npm
             - npm install -g snyk@1.455.0
             - snyk auth $SNYK_TOKEN
             - pipenv run snyk monitor --severity-threshold=high --project-name=dc-deployments-automation
