---
- name: Converge
  hosts: all
  vars:
    atl_product_family: "jira"
    atl_product_edition: "jira-software"
    atl_product_user: "jira"
    atl_product_version: "7.13.2"
    atl_jdbc_user: 'atljira'
    atl_jvm_heap: 'PLACEHOLDER'
    atl_cluster_node_id: 'FAKEID'

  roles:
    - role: linux_common
    - role: product_common
    - role: product_install
    - role: jira_config
