---
- name: Converge
  hosts: all
  vars:
    ansible_ec2_local_ipv4: "1.1.1.1"
    ansible_default_ipv4:
      address: "9.9.9.9"
    ansible_ec2_instance_id: "NONE"

    atl_product_family: "jira"
    atl_product_edition: "jira-software"
    atl_aws_stack_name: "MY_STACK"

    atl_aws_enable_cloudwatch: true
    atl_aws_enable_cloudwatch_logs: false

    atl_aws_agent_restart: false

  roles:
    - role: aws_common
