---
- name: Converge
  hosts: all
  vars:
    atl_product_family: "stash"
    atl_product_edition: "bitbucket"
    atl_product_user: "bitbucket"
  roles:
    - role: linux_common
    - role: product_common
    - role: product_install
