---
- name: Converge
  hosts: all
  vars:
    atl_product_family: "jira"
    atl_product_edition: "jira-core"
    atl_product_user: "jira"
    atl_download_format: "tarball"
  roles:
    - role: linux_common
    - role: product_common
    - role: product_install
