---
- name: Converge
  hosts: all
  vars:
    atl_product_user: "bitbucket"
    atl_product_family: "stash"
    atl_product_edition: "bitbucket"

    atl_startup_systemd_params:
      - "UMask=0027"
      - "LimitNOFILE=4096"
      - "Environment=BITBUCKET_HOME={{ atl_product_home_shared }}"

    atl_startup_exec_options:
      - "-fg"
      - "--no-search"

    atl_startup_enable: false
    atl_startup_restart: false

  pre_tasks:
    - name: Create systemd dir if necessary
      file:
        path: '/etc/systemd/system/'
        state: directory
    
  roles:
    - role: product_startup
