---

# This is the process for most products (except ServiceDesk
# basically). Symlink this to <edition>_version_latest.yml for each
# product that supports the standard marketplace API.

- name: Fetch the latest version from URL
  set_fact:
    atl_product_version_json: "{{ lookup('url', '{{ atl_product_latest_version_url }}') }}"

- name: Set the local var to retrieved version
  set_fact:
    atl_latest_version: "{{ atl_product_version_json._embedded.versions[0].name }}"
